#index:
#    path: /
#    controller: App\Controller\DefaultController::index
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"

app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET, POST]
